name: Coverage

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: macOS 26 AppleClang 21 [Coverage]
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get macOS Concurrency
      run: echo NPROC="sysctl -n hw.ncpu" >> $GITHUB_ENV

    - name: Set Up macOS Dependencies
      run: brew install ninja pkg-config gnupg

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -G "Ninja" -DCOVERAGE=ON

    - name: Build, Test and Generate Code Coverage
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC) --target coverage

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v7.1.1
      with:
        files: ${{runner.workspace}}/build/coverage.info
        disable_search: true
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
