name: Unix

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "macOS 15 AppleClang [Release]",
            os: macos-15,
            cxx: "clang++"
          }
          - {
            name: "macOS 15 GCC 14 [Release]",
            os: macos-15,
            cxx: "g++-14"
          }
          - {
            name: "Ubuntu 24.04 Clang 16 [Release]",
            os: ubuntu-24.04,
            cxx: "clang++-16"
          }
          - {
            name: "Ubuntu 24.04 GCC 12 [Release]",
            os: ubuntu-24.04,
            cxx: "g++-12"
          }

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get macOS Concurrency
      if: runner.os == 'macOS'
      run: |
        echo NPROC="sysctl -n hw.ncpu" >> $GITHUB_ENV
        echo "Running on $(sysctl -n hw.ncpu) threads ..."

    - name: Get Linux Concurrency
      if: runner.os == 'Linux'
      run: |
        echo NPROC="nproc" >> $GITHUB_ENV
        echo "Running on $(nproc) threads ..."

    - name: Set Up macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install ninja gcc@14
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig

    - name: Set Up Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt install -y cmake ninja-build pkg-config clang-16 g++-12

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{runner.workspace}}/conclog -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} -G Ninja

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC)

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -j $($NPROC) --output-on-failure