name: Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Server 2019 [Release]",
            os: windows-2019,
            build-type: "Release"
          }
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{runner.workspace}}/conclog

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel --config ${{matrix.config.build-type}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --output-on-failure